Unauthorized: /login/
"POST /login/ HTTP/1.1" 401 63
WARNING 2021-09-06 10:52:28,105 Not Found: /user/
WARNING 2021-09-06 10:52:28,106 "GET /user/ HTTP/1.1" 404 6253
WARNING 2021-09-06 10:52:35,634 Unauthorized: /users/
WARNING 2021-09-06 10:52:35,635 "GET /users/ HTTP/1.1" 401 183
WARNING 2021-09-06 11:04:08,181 Unauthorized: /users/
WARNING 2021-09-06 11:04:08,182 "GET /users/ HTTP/1.1" 401 183
WARNING 2021-09-06 11:05:04,414 Unauthorized: /users/
WARNING 2021-09-06 11:05:04,414 "GET /users/?profileID=1 HTTP/1.1" 401 183
WARNING 2021-09-06 11:05:17,020 Unauthorized: /users/
WARNING 2021-09-06 11:05:17,020 "GET /users/?profileID=1 HTTP/1.1" 401 183
WARNING 2021-09-06 11:05:43,571 Unauthorized: /users/
WARNING 2021-09-06 11:05:43,571 "GET /users/?profileID=2 HTTP/1.1" 401 183
WARNING 2021-09-06 11:06:10,631 Unauthorized: /users/
WARNING 2021-09-06 11:06:10,631 "GET /users/?profile=5 HTTP/1.1" 401 183
ERROR 2021-09-06 11:06:14,715 Internal Server Error: /users/
Traceback (most recent call last):
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "D:\devapp\projetDAP12\account\views.py", line 41, in get_queryset
    staff_profile = StaffProfile.objects.get(pk = profileID)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\db\models\query.py", line 437, in get
    self.model._meta.object_name
account.models.StaffProfile.DoesNotExist: StaffProfile matching query does not exist.
ERROR 2021-09-06 11:06:14,718 "GET /users/?profile=5 HTTP/1.1" 500 110790
WARNING 2021-09-06 11:06:37,468 Unauthorized: /users/
WARNING 2021-09-06 11:06:37,469 "GET /users/?profile=1 HTTP/1.1" 401 183
WARNING 2021-09-06 11:08:28,548 Unauthorized: /users/
WARNING 2021-09-06 11:08:28,549 "GET /users/?profile=6 HTTP/1.1" 401 183
ERROR 2021-09-06 11:08:33,200 Internal Server Error: /users/
Traceback (most recent call last):
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "D:\devapp\projetDAP12\account\views.py", line 41, in get_queryset
    staff_profile = StaffProfile.objects.get(pk = profileID)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\devapp\projetDAP12\.venv\lib\site-packages\django\db\models\query.py", line 437, in get
    self.model._meta.object_name
account.models.StaffProfile.DoesNotExist: StaffProfile matching query does not exist.
ERROR 2021-09-06 11:08:33,202 "GET /users/?profile=6 HTTP/1.1" 500 110678
WARNING 2021-09-06 11:15:39,695 Unauthorized: /clients/
WARNING 2021-09-06 11:15:39,696 "GET /clients/?contact=1 HTTP/1.1" 401 183
WARNING 2021-09-06 11:15:49,510 Unauthorized: /clients/
WARNING 2021-09-06 11:15:49,511 "GET /clients/?contact=2 HTTP/1.1" 401 183
WARNING 2021-09-06 11:15:56,786 Unauthorized: /clients/
WARNING 2021-09-06 11:15:56,786 "GET /clients/ HTTP/1.1" 401 183
WARNING 2021-09-06 11:16:13,460 Unauthorized: /clients/
WARNING 2021-09-06 11:16:13,460 "GET /clients/?contact=13 HTTP/1.1" 401 183
WARNING 2021-09-06 11:16:36,384 Unauthorized: /clients/
WARNING 2021-09-06 11:16:36,384 "GET /clients/?contact=13&statut=1 HTTP/1.1" 401 183
WARNING 2021-09-06 11:16:45,669 Unauthorized: /clients/
WARNING 2021-09-06 11:16:45,669 "GET /clients/?contact=13&statut=2 HTTP/1.1" 401 183
WARNING 2021-09-06 11:25:07,966 Unauthorized: /contracts/
WARNING 2021-09-06 11:25:07,966 "GET /contracts/ HTTP/1.1" 401 183
WARNING 2021-09-06 11:25:47,081 Unauthorized: /contracts/
WARNING 2021-09-06 11:25:47,081 "GET /contracts/ HTTP/1.1" 401 183
WARNING 2021-09-06 11:26:08,379 Unauthorized: /contracts/
WARNING 2021-09-06 11:26:08,380 "GET /contracts/?client=1 HTTP/1.1" 401 183
WARNING 2021-09-06 11:26:28,251 Unauthorized: /contracts/
WARNING 2021-09-06 11:26:28,251 "GET /contracts/?statut=1 HTTP/1.1" 401 183
